spring.application.name=career-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/skillsphere_db
spring.datasource.username=postgres
spring.datasource.password=Rohan@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
